version: 2

models:
  - name: stg_employees
    columns:
      - name: department_id
        tests:
          - relationships:
              to: ref('stg_departments')
              field: department_id
  - name: departments
    columns:
      - name: department_id
        tests:
          - not_null
          - unique