version: 2

sources:
  - name: hr
    database: dbt
    schema: hr
    tables:
      - name: src_employees
        loaded_at_field: LOAD_TIME
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
            
        