version: 2

sources:
  - name: hr
    database: dbt
    schema: hr
    tables:
      - name: src_employees
        columns:
          - name: employee_id
            tests:
              - not_null
              - unique
      
      - name: departments

            
        